import { Doctor, Chemist, Product, UserProfile, RoutePlan, Hospital, StockistFirm, MonthlyTourProgramme } from '../types';

export const CURRENT_USER: UserProfile = {
  id: 'usr-mr-barak-01',
  name: 'Shakir Ahmad',
  email: 'shakirahmad878@gmail.com',
  role: 'MEDICAL_REP',
  employeeCode: 'REP-AS-904',
  territory: 'Barak Valley Division (Assam)',
  headquarter: 'Silchar HQ',
  phone: '+91 8448440654',
  assignedRouteIds: [
    'route-cachar-01',
    'route-cachar-02',
    'route-cachar-03',
    'route-karimganj-01',
    'route-karimganj-02',
    'route-hailakandi-01',
  ],
  activeRouteId: 'route-cachar-01',
};

export const BARAK_ROUTES: RoutePlan[] = [
  {
    id: 'route-cachar-01',
    code: 'ROUTE-SIL-01',
    name: 'Silchar Central - SMCH & Hospital Road',
    district: 'Cachar',
    areas: ['SMCH Ghungoor', 'Hospital Road', 'Park Road', 'Ambicapatty', 'College Road'],
    totalDoctors: 16,
    totalHospitals: 6,
    totalChemists: 22,
    isAssigned: true,
    isActiveToday: true,
    description: 'Tertiary medical college & polyclinic core corridor in Silchar.',
  },
  {
    id: 'route-cachar-02',
    code: 'ROUTE-SIL-02',
    name: 'Silchar North - Tarapur, Rangirkhari & Meherpur',
    district: 'Cachar',
    areas: ['Tarapur', 'Rangirkhari Point', 'Meherpur', 'Malugram', 'Sadarghat', 'Kanakpur'],
    totalDoctors: 14,
    totalHospitals: 4,
    totalChemists: 18,
    isAssigned: true,
    isActiveToday: false,
    description: 'Commercial nursing home and specialty chamber belt.',
  },
  {
    id: 'route-karimganj-01',
    code: 'ROUTE-KXJ-01',
    name: 'Karimganj Town & Station Road Hub (Shribhumi)',
    district: 'Karimganj',
    areas: ['Civil Hospital Road', 'Station Road', 'Settlement Area', 'Main Road', 'Charbazar'],
    totalDoctors: 12,
    totalHospitals: 3,
    totalChemists: 16,
    isAssigned: true,
    isActiveToday: false,
    description: 'District headquarters healthcare and wholesale distributor hub in Karimganj (Shribhumi).',
  },
  {
    id: 'route-karimganj-02',
    code: 'ROUTE-BDP-02',
    name: 'Badarpur Junction, RK Nagar & Nilambazar (Shribhumi)',
    district: 'Karimganj',
    areas: ['Badarpur Railway Town', 'Ram Krishna Nagar', 'Nilambazar', 'Patharkandi'],
    totalDoctors: 10,
    totalHospitals: 2,
    totalChemists: 14,
    isAssigned: true,
    isActiveToday: false,
    description: 'Northern junction corridor and rural community health centers.',
  },
  {
    id: 'route-hailakandi-01',
    code: 'ROUTE-HKD-01',
    name: 'Hailakandi Main, S.K. Roy & Lala Bazar Belt',
    district: 'Hailakandi',
    areas: ['S.K. Roy Hospital Road', 'Station Road', 'Rabindra Sarani', 'Lala Bazar', 'Katlicherra', 'Algapur'],
    totalDoctors: 12,
    totalHospitals: 4,
    totalChemists: 15,
    isAssigned: true,
    isActiveToday: false,
    description: 'Hailakandi district hospital and South Barak retail pharmacy market.',
  },
  {
    id: 'route-cachar-03',
    code: 'ROUTE-RURAL-03',
    name: 'Lakhipur, Sonai & Rural Cachar Circuit',
    district: 'Cachar',
    areas: ['Lakhipur Subdivision', 'Sonai Bazar', 'Dholai', 'Udharbond', 'Borkhola', 'Katigorah'],
    totalDoctors: 8,
    totalHospitals: 3,
    totalChemists: 12,
    isAssigned: true,
    isActiveToday: false,
    description: 'Peripheral subdivision clinics, CHCs, and tea garden hospital network.',
  },
];

export const BARAK_HOSPITALS: Hospital[] = [
  // Cachar / Silchar
  {
    id: 'hosp-01',
    name: 'Silchar Medical College & Hospital (SMCH)',
    type: 'GOVERNMENT_MEDICAL_COLLEGE',
    district: 'Cachar',
    area: 'Ghungoor, Silchar',
    address: 'Ghungoor, Silchar, Cachar, Assam 788014',
    bedCount: 1000,
    keyDoctorsCount: 22,
    latitude: 24.7766,
    longitude: 92.7938,
    phone: '+91 3842 229110',
    routeId: 'route-cachar-01',
  },
  {
    id: 'hosp-02',
    name: 'Valley Hospital & Research Centre',
    type: 'PRIVATE_HOSPITAL',
    district: 'Cachar',
    area: 'Meherpur, Silchar',
    address: 'National Highway 54, Meherpur, Silchar, Assam 788015',
    bedCount: 180,
    keyDoctorsCount: 12,
    latitude: 24.8012,
    longitude: 92.7845,
    phone: '+91 3842 242000',
    routeId: 'route-cachar-02',
  },
  {
    id: 'hosp-03',
    name: 'Green Heals Hospital',
    type: 'PRIVATE_HOSPITAL',
    district: 'Cachar',
    area: 'Hospital Road, Silchar',
    address: 'Hospital Road, Ambicapatty, Silchar, Assam 788005',
    bedCount: 140,
    keyDoctorsCount: 9,
    latitude: 24.8219,
    longitude: 92.7972,
    phone: '+91 3842 233444',
    routeId: 'route-cachar-01',
  },
  {
    id: 'hosp-04',
    name: 'Nightingale Hospital & Nursing Home',
    type: 'NURSING_HOME',
    district: 'Cachar',
    area: 'Rangirkhari, Silchar',
    address: 'Rangirkhari Point, Silchar, Assam 788005',
    bedCount: 90,
    keyDoctorsCount: 7,
    latitude: 24.8142,
    longitude: 92.7911,
    phone: '+91 3842 260111',
    routeId: 'route-cachar-02',
  },
  {
    id: 'hosp-05',
    name: 'Lions Eye & Superspeciality Hospital',
    type: 'EYE_HOSPITAL',
    district: 'Cachar',
    area: 'Park Road, Silchar',
    address: 'Park Road, Silchar, Assam 788001',
    bedCount: 75,
    keyDoctorsCount: 5,
    latitude: 24.8248,
    longitude: 92.7985,
    phone: '+91 3842 245678',
    routeId: 'route-cachar-01',
  },
  {
    id: 'hosp-06',
    name: 'Barak Valley Nursing Home',
    type: 'NURSING_HOME',
    district: 'Cachar',
    area: 'College Road, Silchar',
    address: 'College Road, Ambicapatty, Silchar 788005',
    bedCount: 60,
    keyDoctorsCount: 6,
    latitude: 24.8190,
    longitude: 92.7950,
    phone: '+91 3842 231122',
    routeId: 'route-cachar-01',
  },
  {
    id: 'hosp-07',
    name: 'Deshabandhu Multi-Speciality Hospital',
    type: 'PRIVATE_HOSPITAL',
    district: 'Cachar',
    area: 'Tarapur, Silchar',
    address: 'Station Road, Tarapur, Silchar 788003',
    bedCount: 70,
    keyDoctorsCount: 5,
    latitude: 24.8325,
    longitude: 92.7885,
    phone: '+91 3842 254321',
    routeId: 'route-cachar-02',
  },
  {
    id: 'hosp-08',
    name: 'Gracewell Hospital & Trauma Centre',
    type: 'PRIVATE_HOSPITAL',
    district: 'Cachar',
    area: 'Malugram, Silchar',
    address: 'Malugram Road, Silchar 788002',
    bedCount: 80,
    keyDoctorsCount: 6,
    latitude: 24.8390,
    longitude: 92.7980,
    phone: '+91 3842 278900',
    routeId: 'route-cachar-02',
  },
  {
    id: 'hosp-09',
    name: 'Lakhipur Subdivisional Civil Hospital',
    type: 'CIVIL_HOSPITAL',
    district: 'Cachar',
    area: 'Lakhipur Subdivision',
    address: 'Lakhipur Town, Cachar 788103',
    bedCount: 100,
    keyDoctorsCount: 5,
    latitude: 24.7955,
    longitude: 93.0120,
    phone: '+91 3842 287111',
    routeId: 'route-cachar-03',
  },
  {
    id: 'hosp-10',
    name: 'Sonai First Referral Unit (FRU)',
    type: 'COMMUNITY_HEALTH_CENTRE',
    district: 'Cachar',
    area: 'Sonai Bazar',
    address: 'Sonai Main Road, Cachar 788119',
    bedCount: 50,
    keyDoctorsCount: 4,
    latitude: 24.7210,
    longitude: 92.8950,
    phone: '+91 3842 274222',
    routeId: 'route-cachar-03',
  },

  // Karimganj / Shribhumi
  {
    id: 'hosp-11',
    name: 'Karimganj Civil Hospital (Shribhumi)',
    type: 'CIVIL_HOSPITAL',
    district: 'Karimganj',
    area: 'Civil Hospital Road, Karimganj',
    address: 'Civil Hospital Road, Karimganj (Shribhumi), Assam 788710',
    bedCount: 250,
    keyDoctorsCount: 10,
    latitude: 24.8682,
    longitude: 92.3551,
    phone: '+91 3843 262222',
    routeId: 'route-karimganj-01',
  },
  {
    id: 'hosp-12',
    name: 'Indian Red Cross Hospital',
    type: 'PRIVATE_HOSPITAL',
    district: 'Karimganj',
    area: 'Station Road, Karimganj',
    address: 'Station Road, Karimganj 788710',
    bedCount: 80,
    keyDoctorsCount: 6,
    latitude: 24.8695,
    longitude: 92.3570,
    phone: '+91 3843 264500',
    routeId: 'route-karimganj-01',
  },
  {
    id: 'hosp-13',
    name: 'Badarpur Railway Hospital',
    type: 'CIVIL_HOSPITAL',
    district: 'Karimganj',
    area: 'Badarpur Junction',
    address: 'Railway Colony, Badarpur, Karimganj 788806',
    bedCount: 75,
    keyDoctorsCount: 4,
    latitude: 24.9015,
    longitude: 92.5440,
    phone: '+91 3845 268100',
    routeId: 'route-karimganj-02',
  },
  {
    id: 'hosp-14',
    name: 'Ram Krishna Nagar Model Hospital',
    type: 'COMMUNITY_HEALTH_CENTRE',
    district: 'Karimganj',
    area: 'RK Nagar',
    address: 'Main Road, Ram Krishna Nagar 788166',
    bedCount: 50,
    keyDoctorsCount: 4,
    latitude: 24.5800,
    longitude: 92.4900,
    phone: '+91 3843 277200',
    routeId: 'route-karimganj-02',
  },
  {
    id: 'hosp-15',
    name: 'Patharkandi First Referral Unit',
    type: 'COMMUNITY_HEALTH_CENTRE',
    district: 'Karimganj',
    area: 'Patharkandi',
    address: 'Patharkandi Town, Karimganj 788724',
    bedCount: 50,
    keyDoctorsCount: 3,
    latitude: 24.6200,
    longitude: 92.3300,
    phone: '+91 3843 288300',
    routeId: 'route-karimganj-02',
  },

  // Hailakandi
  {
    id: 'hosp-16',
    name: 'S.K. Roy Civil Hospital',
    type: 'CIVIL_HOSPITAL',
    district: 'Hailakandi',
    area: 'Hospital Road, Hailakandi',
    address: 'Hospital Road, Hailakandi Town, Assam 788151',
    bedCount: 200,
    keyDoctorsCount: 8,
    latitude: 24.6833,
    longitude: 92.5667,
    phone: '+91 3844 222111',
    routeId: 'route-hailakandi-01',
  },
  {
    id: 'hosp-17',
    name: 'Lala Community Health Centre',
    type: 'COMMUNITY_HEALTH_CENTRE',
    district: 'Hailakandi',
    area: 'Lala Bazar',
    address: 'Main Road, Lala Town, Hailakandi 788163',
    bedCount: 60,
    keyDoctorsCount: 4,
    latitude: 24.5510,
    longitude: 92.6015,
    phone: '+91 3844 244200',
    routeId: 'route-hailakandi-01',
  },
  {
    id: 'hosp-18',
    name: 'Katlicherra Model Hospital',
    type: 'COMMUNITY_HEALTH_CENTRE',
    district: 'Hailakandi',
    area: 'Katlicherra',
    address: 'Katlicherra Bazar, Hailakandi 788161',
    bedCount: 40,
    keyDoctorsCount: 3,
    latitude: 24.4600,
    longitude: 92.5700,
    phone: '+91 3844 266100',
    routeId: 'route-hailakandi-01',
  },
];

export const BARAK_FIRMS: StockistFirm[] = [
  // Cachar
  {
    id: 'firm-01',
    name: 'Barak Pharma Distributors',
    contactPerson: 'Pradip Roy',
    type: 'SUPER_STOCKIST',
    dlNumber: 'AS-CAC-2023-DL-0891',
    gstNumber: '18AAACB1234F1Z1',
    district: 'Cachar',
    area: 'Hospital Road, Silchar',
    address: '42 Hospital Road, Near Lions Club, Silchar 788005',
    phone: '+91 9435071234',
    routeId: 'route-cachar-01',
  },
  {
    id: 'firm-02',
    name: 'Cachar Drug Agencies',
    contactPerson: 'Debashis Paul',
    type: 'AUTHORIZED_DISTRIBUTOR',
    dlNumber: 'AS-CAC-2022-DL-0452',
    gstNumber: '18AACCD5678G2Z4',
    district: 'Cachar',
    area: 'Tarapur, Silchar',
    address: 'Station Road, Tarapur, Silchar 788003',
    phone: '+91 9435175678',
    routeId: 'route-cachar-02',
  },
  {
    id: 'firm-03',
    name: 'City Medico Agencies',
    contactPerson: 'Subir Das',
    type: 'WHOLESALE_PHARMA',
    dlNumber: 'AS-CAC-2021-DL-0992',
    gstNumber: '18AACCJ8876H3Z8',
    district: 'Cachar',
    area: 'Rangirkhari, Silchar',
    address: 'Rangirkhari Point, Silchar 788005',
    phone: '+91 9435081122',
    routeId: 'route-cachar-02',
  },
  {
    id: 'firm-04',
    name: 'Eastern Drug Syndicate',
    contactPerson: 'Manoj Bhattacharjee',
    type: 'AUTHORIZED_DISTRIBUTOR',
    dlNumber: 'AS-CAC-2023-DL-0312',
    gstNumber: '18AACCE4433J4Z2',
    district: 'Cachar',
    area: 'Ambicapatty, Silchar',
    address: 'Ambicapatty Main Road, Silchar 788004',
    phone: '+91 9435092233',
    routeId: 'route-cachar-01',
  },
  {
    id: 'firm-05',
    name: 'Pioneer Pharma Wholesale',
    contactPerson: 'Anup Choudhury',
    type: 'WHOLESALE_PHARMA',
    dlNumber: 'AS-CAC-2020-DL-0144',
    gstNumber: '18AACCP1199K5Z1',
    district: 'Cachar',
    area: 'Malugram, Silchar',
    address: 'Malugram Bazar, Silchar 788002',
    phone: '+91 9435103344',
    routeId: 'route-cachar-02',
  },
  {
    id: 'firm-06',
    name: 'Sun Medical Agencies',
    contactPerson: 'Ranjan Nath',
    type: 'AUTHORIZED_DISTRIBUTOR',
    dlNumber: 'AS-CAC-2024-DL-0601',
    gstNumber: '18AACCS7788L6Z7',
    district: 'Cachar',
    area: 'Ghungoor, Silchar',
    address: 'Opposite SMCH Gate 2, Ghungoor, Silchar 788014',
    phone: '+91 9435114455',
    routeId: 'route-cachar-01',
  },
  {
    id: 'firm-07',
    name: 'Surma Valley Drug Corporation',
    contactPerson: 'Biswajit Dey',
    type: 'WHOLESALE_PHARMA',
    dlNumber: 'AS-CAC-2022-DL-0731',
    gstNumber: '18AACCB3322M7Z9',
    district: 'Cachar',
    area: 'Park Road, Silchar',
    address: 'Park Road Corner, Silchar 788001',
    phone: '+91 9435125566',
    routeId: 'route-cachar-01',
  },
  {
    id: 'firm-08',
    name: 'Lakhipur Medico Distributors',
    contactPerson: 'Bimal Sinha',
    type: 'AUTHORIZED_DISTRIBUTOR',
    dlNumber: 'AS-CAC-2021-DL-0288',
    gstNumber: '18AACCL9911N8Z3',
    district: 'Cachar',
    area: 'Lakhipur Town',
    address: 'Bazar Road, Lakhipur, Cachar 788103',
    phone: '+91 9435136677',
    routeId: 'route-cachar-03',
  },

  // Karimganj / Shribhumi
  {
    id: 'firm-09',
    name: 'Surma Valley Medical Syndicate (Shribhumi)',
    contactPerson: 'Alok Choudhury',
    type: 'SUPER_STOCKIST',
    dlNumber: 'AS-KXJ-2021-DL-0311',
    gstNumber: '18AAECS9012H3Z9',
    district: 'Karimganj',
    area: 'Settlement Road, Karimganj',
    address: 'Settlement Road, Near Old Court, Karimganj 788710',
    phone: '+91 9435278901',
    routeId: 'route-karimganj-01',
  },
  {
    id: 'firm-10',
    name: 'Shribhumi Medico Agencies',
    contactPerson: 'Nirmal Paul',
    type: 'AUTHORIZED_DISTRIBUTOR',
    dlNumber: 'AS-KXJ-2023-DL-0551',
    gstNumber: '18AAECS6655P1Z8',
    district: 'Karimganj',
    area: 'Station Road, Karimganj',
    address: 'Station Road, Near Town Club, Karimganj 788710',
    phone: '+91 9435289900',
    routeId: 'route-karimganj-01',
  },
  {
    id: 'firm-11',
    name: 'Karimganj Drug House',
    contactPerson: 'Sujit Deb',
    type: 'WHOLESALE_PHARMA',
    dlNumber: 'AS-KXJ-2020-DL-0192',
    gstNumber: '18AAECK1122Q2Z6',
    district: 'Karimganj',
    area: 'Civil Hospital Road, Karimganj',
    address: 'Hospital Road, Karimganj 788710',
    phone: '+91 9435291122',
    routeId: 'route-karimganj-01',
  },
  {
    id: 'firm-12',
    name: 'Badarpur Pharma Link',
    contactPerson: 'Kabir Ahmed',
    type: 'AUTHORIZED_DISTRIBUTOR',
    dlNumber: 'AS-KXJ-2022-DL-0481',
    gstNumber: '18AAECB4433R3Z4',
    district: 'Karimganj',
    area: 'Badarpur Junction',
    address: 'Station Road, Badarpur, Karimganj 788806',
    phone: '+91 9435302233',
    routeId: 'route-karimganj-02',
  },
  {
    id: 'firm-13',
    name: 'Ram Krishna Nagar Medico',
    contactPerson: 'Dilip Roy',
    type: 'WHOLESALE_PHARMA',
    dlNumber: 'AS-KXJ-2021-DL-0610',
    gstNumber: '18AAECR8899S4Z2',
    district: 'Karimganj',
    area: 'RK Nagar',
    address: 'Main Market, Ram Krishna Nagar 788166',
    phone: '+91 9435313344',
    routeId: 'route-karimganj-02',
  },

  // Hailakandi
  {
    id: 'firm-14',
    name: 'Barak Medico Agencies (Hailakandi)',
    contactPerson: 'Sudhir Nath',
    type: 'SUPER_STOCKIST',
    dlNumber: 'AS-HKD-2024-DL-0199',
    gstNumber: '18AAEFN3456J4Z7',
    district: 'Hailakandi',
    area: 'Station Road, Hailakandi',
    address: 'Station Road, Hailakandi Town 788151',
    phone: '+91 9435371122',
    routeId: 'route-hailakandi-01',
  },
  {
    id: 'firm-15',
    name: 'Hailakandi Drug House',
    contactPerson: 'Gopal Roy',
    type: 'AUTHORIZED_DISTRIBUTOR',
    dlNumber: 'AS-HKD-2022-DL-0341',
    gstNumber: '18AAEPH2211T5Z0',
    district: 'Hailakandi',
    area: 'Hospital Road, Hailakandi',
    address: 'Opposite S.K. Roy Hospital, Hailakandi 788151',
    phone: '+91 9435382233',
    routeId: 'route-hailakandi-01',
  },
  {
    id: 'firm-16',
    name: 'Lala Pharma Syndicate',
    contactPerson: 'Tarun Paul',
    type: 'WHOLESALE_PHARMA',
    dlNumber: 'AS-HKD-2023-DL-0512',
    gstNumber: '18AAEPL7766U6Z8',
    district: 'Hailakandi',
    area: 'Lala Bazar',
    address: 'Main Road, Lala Town, Hailakandi 788163',
    phone: '+91 9435393344',
    routeId: 'route-hailakandi-01',
  },
];

export const MOCK_DOCTORS: Doctor[] = [
  // Cachar - Silchar Central (Route 1)
  {
    id: 'doc-sil-01',
    name: 'Dr. Sanjay Solanki',
    qualification: 'MD (General Medicine), DM (Cardiology)',
    specialty: 'Cardiologist',
    tier: 'A_PLUS',
    clinicName: 'Silchar Heart & Vascular Care Centre',
    clinicAddress: '14 Hospital Road, Ambicapatty, Silchar 788005',
    district: 'Cachar',
    area: 'Hospital Road',
    routeId: 'route-cachar-01',
    latitude: 24.8215,
    longitude: 92.7970,
    geofenceRadiusMeters: 100,
    phone: '+91 9435012345',
    monthlyVisitTarget: 10,
    completedVisitsThisMonth: 1,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-sil-02',
    name: 'Dr. Vijay Thakur',
    qualification: 'MS (Orthopedics), M.Ch (Joint Replacement)',
    specialty: 'Orthopedic Surgeon',
    tier: 'A_PLUS',
    clinicName: 'Barak Ortho Spine & Trauma Clinic',
    clinicAddress: 'Opposite SMCH Main Gate, Ghungoor, Silchar 788014',
    district: 'Cachar',
    area: 'SMCH Ghungoor',
    routeId: 'route-cachar-01',
    latitude: 24.7770,
    longitude: 92.7942,
    geofenceRadiusMeters: 100,
    phone: '+91 9435023456',
    monthlyVisitTarget: 10,
    completedVisitsThisMonth: 2,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-sil-03',
    name: 'Dr. Debashis Nath',
    qualification: 'MD (Pediatrics), DCH',
    specialty: 'Pediatrician',
    tier: 'A',
    clinicName: 'Cachar Children Care Clinic',
    clinicAddress: 'Park Road, Near Normal School, Silchar 788001',
    district: 'Cachar',
    area: 'Park Road',
    routeId: 'route-cachar-01',
    latitude: 24.8250,
    longitude: 92.7990,
    geofenceRadiusMeters: 100,
    phone: '+91 9435034567',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 2,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-sil-04',
    name: 'Dr. Ratan Paul',
    qualification: 'MD (Internal Medicine)',
    specialty: 'Consultant Physician',
    tier: 'A',
    clinicName: 'Green Heals Poly Clinic',
    clinicAddress: 'Hospital Road, Ambicapatty, Silchar 788005',
    district: 'Cachar',
    area: 'Hospital Road',
    routeId: 'route-cachar-01',
    latitude: 24.8220,
    longitude: 92.7975,
    geofenceRadiusMeters: 100,
    phone: '+91 9435045678',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 3,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-sil-05',
    name: 'Dr. Tanmoy Bhattacharjee',
    qualification: 'MD (Medicine), DM (Neurology)',
    specialty: 'Neurologist',
    tier: 'A_PLUS',
    clinicName: 'SMCH Neuro Chamber',
    clinicAddress: 'Super-Specialty Block, SMCH Ghungoor, Silchar 788014',
    district: 'Cachar',
    area: 'SMCH Ghungoor',
    routeId: 'route-cachar-01',
    latitude: 24.7768,
    longitude: 92.7940,
    geofenceRadiusMeters: 100,
    phone: '+91 9435051122',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-sil-06',
    name: 'Dr. Ananya Roy Choudhury',
    qualification: 'MD (Obstetrics & Gynecology)',
    specialty: 'Gynecologist',
    tier: 'A_PLUS',
    clinicName: 'Barak Valley Mother Care',
    clinicAddress: 'College Road, Ambicapatty, Silchar 788005',
    district: 'Cachar',
    area: 'College Road',
    routeId: 'route-cachar-01',
    latitude: 24.8195,
    longitude: 92.7955,
    geofenceRadiusMeters: 100,
    phone: '+91 9435062233',
    monthlyVisitTarget: 10,
    completedVisitsThisMonth: 1,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-sil-07',
    name: 'Dr. Pinaki Chakraborty',
    qualification: 'MS (Ophthalmology)',
    specialty: 'Eye Specialist',
    tier: 'B',
    clinicName: 'Lions Eye Centre',
    clinicAddress: 'Park Road, Silchar 788001',
    district: 'Cachar',
    area: 'Park Road',
    routeId: 'route-cachar-01',
    latitude: 24.8245,
    longitude: 92.7980,
    geofenceRadiusMeters: 100,
    phone: '+91 9435073344',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-sil-08',
    name: 'Dr. Abhijit Das',
    qualification: 'MD (Dermatology)',
    specialty: 'Dermatologist',
    tier: 'A',
    clinicName: 'Silchar Skin Laser Clinic',
    clinicAddress: 'Hospital Road, Silchar 788005',
    district: 'Cachar',
    area: 'Hospital Road',
    routeId: 'route-cachar-01',
    latitude: 24.8210,
    longitude: 92.7968,
    geofenceRadiusMeters: 100,
    phone: '+91 9435084455',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },

  // Cachar - Silchar North & Commercial (Route 2)
  {
    id: 'doc-sil-09',
    name: 'Dr. Anupama Bhattacharjee',
    qualification: 'MD (Obstetrics & Gynecology), DGO',
    specialty: 'Gynecologist',
    tier: 'A_PLUS',
    clinicName: 'Matri Kalyan Clinic',
    clinicAddress: 'Rangirkhari Point, Silchar 788005',
    district: 'Cachar',
    area: 'Rangirkhari',
    routeId: 'route-cachar-02',
    latitude: 24.8140,
    longitude: 92.7915,
    geofenceRadiusMeters: 100,
    phone: '+91 9435056789',
    monthlyVisitTarget: 10,
    completedVisitsThisMonth: 1,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-sil-10',
    name: 'Dr. Subhashish Deb',
    qualification: 'MS (General Surgery), FIAGES',
    specialty: 'General Surgeon',
    tier: 'A',
    clinicName: 'Valley Research Chamber',
    clinicAddress: 'Meherpur, Silchar 788015',
    district: 'Cachar',
    area: 'Meherpur',
    routeId: 'route-cachar-02',
    latitude: 24.8015,
    longitude: 92.7850,
    geofenceRadiusMeters: 100,
    phone: '+91 9435067890',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-sil-11',
    name: 'Dr. Nilanjan Roy',
    qualification: 'MD (Dermatology, Venereology & Leprosy)',
    specialty: 'Dermatologist',
    tier: 'B',
    clinicName: 'Tarapur Skin & Laser Care',
    clinicAddress: 'Station Road, Tarapur, Silchar 788003',
    district: 'Cachar',
    area: 'Tarapur',
    routeId: 'route-cachar-02',
    latitude: 24.8320,
    longitude: 92.7880,
    geofenceRadiusMeters: 100,
    phone: '+91 9435078901',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-sil-12',
    name: 'Dr. Kaushik Dey',
    qualification: 'MD (Chest Medicine), FCCP',
    specialty: 'Pulmonologist',
    tier: 'A',
    clinicName: 'Nightingale Respiratory Clinic',
    clinicAddress: 'Rangirkhari Point, Silchar 788005',
    district: 'Cachar',
    area: 'Rangirkhari',
    routeId: 'route-cachar-02',
    latitude: 24.8145,
    longitude: 92.7918,
    geofenceRadiusMeters: 100,
    phone: '+91 9435095566',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-sil-13',
    name: 'Dr. Sujit Nath',
    qualification: 'MS (ENT), DLO',
    specialty: 'ENT Specialist',
    tier: 'B',
    clinicName: 'Tarapur ENT Care',
    clinicAddress: 'Station Road, Tarapur, Silchar 788003',
    district: 'Cachar',
    area: 'Tarapur',
    routeId: 'route-cachar-02',
    latitude: 24.8328,
    longitude: 92.7882,
    geofenceRadiusMeters: 100,
    phone: '+91 9435106677',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-sil-14',
    name: 'Dr. Joydeep Paul',
    qualification: 'MD (Psychiatry)',
    specialty: 'Psychiatrist',
    tier: 'B',
    clinicName: 'Malugram Mind Health Clinic',
    clinicAddress: 'Malugram Bazar Road, Silchar 788002',
    district: 'Cachar',
    area: 'Malugram',
    routeId: 'route-cachar-02',
    latitude: 24.8395,
    longitude: 92.7985,
    geofenceRadiusMeters: 100,
    phone: '+91 9435117788',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },

  // Karimganj / Shribhumi Town (Route 3)
  {
    id: 'doc-kxj-01',
    name: 'Dr. Sourav Choudhury',
    qualification: 'MD (Chest Medicine), FCCP',
    specialty: 'Pulmonologist',
    tier: 'A',
    clinicName: 'Karimganj Chest & Asthma Clinic',
    clinicAddress: 'Civil Hospital Road, Karimganj (Shribhumi) 788710',
    district: 'Karimganj',
    area: 'Civil Hospital Road',
    routeId: 'route-karimganj-01',
    latitude: 24.8685,
    longitude: 92.3555,
    geofenceRadiusMeters: 100,
    phone: '+91 9435089012',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 1,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-kxj-02',
    name: 'Dr. Monojit Roy',
    qualification: 'MD (General Medicine)',
    specialty: 'Physician & Diabetologist',
    tier: 'A',
    clinicName: 'Surma Medical Chamber',
    clinicAddress: 'Station Road, Near Town Club, Karimganj 788710',
    district: 'Karimganj',
    area: 'Station Road',
    routeId: 'route-karimganj-01',
    latitude: 24.8690,
    longitude: 92.3560,
    geofenceRadiusMeters: 100,
    phone: '+91 9435090123',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-kxj-03',
    name: 'Dr. Subir Sen',
    qualification: 'MS (Orthopedics)',
    specialty: 'Orthopedic Surgeon',
    tier: 'A',
    clinicName: 'Shribhumi Bone & Joint Clinic',
    clinicAddress: 'Settlement Road, Karimganj 788710',
    district: 'Karimganj',
    area: 'Settlement Area',
    routeId: 'route-karimganj-01',
    latitude: 24.8670,
    longitude: 92.3540,
    geofenceRadiusMeters: 100,
    phone: '+91 9435128899',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-kxj-04',
    name: 'Dr. Nandita Das',
    qualification: 'MD (Pediatrics), DCH',
    specialty: 'Pediatrician',
    tier: 'A',
    clinicName: 'Shribhumi Child Care Centre',
    clinicAddress: 'Main Road, Karimganj 788710',
    district: 'Karimganj',
    area: 'Main Road',
    routeId: 'route-karimganj-01',
    latitude: 24.8675,
    longitude: 92.3550,
    geofenceRadiusMeters: 100,
    phone: '+91 9435139900',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-kxj-05',
    name: 'Dr. Ashim Paul',
    qualification: 'MS (General Surgery)',
    specialty: 'General Surgeon',
    tier: 'B',
    clinicName: 'Civil Hospital Surgi Care',
    clinicAddress: 'Hospital Road, Karimganj 788710',
    district: 'Karimganj',
    area: 'Civil Hospital Road',
    routeId: 'route-karimganj-01',
    latitude: 24.8680,
    longitude: 92.3552,
    geofenceRadiusMeters: 100,
    phone: '+91 9435140011',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },

  // Karimganj / Shribhumi - Badarpur & RK Nagar (Route 4)
  {
    id: 'doc-bdp-01',
    name: 'Dr. Shahin Ahmed',
    qualification: 'MD (Internal Medicine)',
    specialty: 'Consultant Physician',
    tier: 'A',
    clinicName: 'Badarpur Junction Poly Clinic',
    clinicAddress: 'Station Road, Badarpur, Karimganj 788806',
    district: 'Karimganj',
    area: 'Badarpur Railway Town',
    routeId: 'route-karimganj-02',
    latitude: 24.9018,
    longitude: 92.5445,
    geofenceRadiusMeters: 100,
    phone: '+91 9435151122',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-bdp-02',
    name: 'Dr. Biswadeep Roy',
    qualification: 'MD (Pediatrics)',
    specialty: 'Child Specialist',
    tier: 'B',
    clinicName: 'Nilambazar Child Clinic',
    clinicAddress: 'Bazar Road, Nilambazar, Karimganj 788722',
    district: 'Karimganj',
    area: 'Nilambazar',
    routeId: 'route-karimganj-02',
    latitude: 24.7800,
    longitude: 92.3900,
    geofenceRadiusMeters: 100,
    phone: '+91 9435162233',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-bdp-03',
    name: 'Dr. Pradeep Sinha',
    qualification: 'MS (Orthopedics)',
    specialty: 'Orthopedic Consultant',
    tier: 'B',
    clinicName: 'Ram Krishna Nagar Clinic',
    clinicAddress: 'Main Road, RK Nagar 788166',
    district: 'Karimganj',
    area: 'Ram Krishna Nagar',
    routeId: 'route-karimganj-02',
    latitude: 24.5805,
    longitude: 92.4905,
    geofenceRadiusMeters: 100,
    phone: '+91 9435173344',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-bdp-04',
    name: 'Dr. Mofizur Rahman',
    qualification: 'MBBS, DGO',
    specialty: 'Gynecologist',
    tier: 'B',
    clinicName: 'Patharkandi Mother Care',
    clinicAddress: 'Town Point, Patharkandi 788724',
    district: 'Karimganj',
    area: 'Patharkandi',
    routeId: 'route-karimganj-02',
    latitude: 24.6205,
    longitude: 92.3305,
    geofenceRadiusMeters: 100,
    phone: '+91 9435184455',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },

  // Hailakandi Main & Lala Belt (Route 5)
  {
    id: 'doc-hkd-01',
    name: 'Dr. Pranab Nath',
    qualification: 'MD (Medicine), DM (Gastroenterology)',
    specialty: 'Gastroenterologist',
    tier: 'A_PLUS',
    clinicName: 'Hailakandi Gastro Liver Clinic',
    clinicAddress: 'Hospital Road, Near S.K. Roy Hospital, Hailakandi 788151',
    district: 'Hailakandi',
    area: 'Hospital Road',
    routeId: 'route-hailakandi-01',
    latitude: 24.6835,
    longitude: 92.5670,
    geofenceRadiusMeters: 100,
    phone: '+91 9435101234',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-hkd-02',
    name: 'Dr. Bikramjit Sinha',
    qualification: 'MS (ENT), DLO',
    specialty: 'ENT Specialist',
    tier: 'B',
    clinicName: 'Lala Bazar Health Clinic',
    clinicAddress: 'Main Road, Lala Bazar, Hailakandi 788163',
    district: 'Hailakandi',
    area: 'Lala Bazar',
    routeId: 'route-hailakandi-01',
    latitude: 24.5500,
    longitude: 92.6000,
    geofenceRadiusMeters: 100,
    phone: '+91 9435112345',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-hkd-03',
    name: 'Dr. Manas Roy',
    qualification: 'MD (General Medicine)',
    specialty: 'Consultant Physician',
    tier: 'A',
    clinicName: 'Hailakandi Med Center',
    clinicAddress: 'Station Road, Hailakandi Town 788151',
    district: 'Hailakandi',
    area: 'Station Road',
    routeId: 'route-hailakandi-01',
    latitude: 24.6840,
    longitude: 92.5680,
    geofenceRadiusMeters: 100,
    phone: '+91 9435195566',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-hkd-04',
    name: 'Dr. Jharna Das',
    qualification: 'MD (Pediatrics)',
    specialty: 'Pediatrician',
    tier: 'A',
    clinicName: 'S.K. Roy Shishu Care',
    clinicAddress: 'Hospital Road, Hailakandi 788151',
    district: 'Hailakandi',
    area: 'Hospital Road',
    routeId: 'route-hailakandi-01',
    latitude: 24.6830,
    longitude: 92.5665,
    geofenceRadiusMeters: 100,
    phone: '+91 9435206677',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-hkd-05',
    name: 'Dr. Sujit Paul',
    qualification: 'MS (General Surgery)',
    specialty: 'General Surgeon',
    tier: 'B',
    clinicName: 'Rabindra Sarani Clinic',
    clinicAddress: 'Rabindra Sarani, Hailakandi 788151',
    district: 'Hailakandi',
    area: 'Rabindra Sarani',
    routeId: 'route-hailakandi-01',
    latitude: 24.6820,
    longitude: 92.5650,
    geofenceRadiusMeters: 100,
    phone: '+91 9435217788',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-hkd-06',
    name: 'Dr. Faruk Ahmed',
    qualification: 'MBBS, DCH',
    specialty: 'General Physician',
    tier: 'B',
    clinicName: 'Katlicherra Rural Health Clinic',
    clinicAddress: 'Main Road, Katlicherra 788161',
    district: 'Hailakandi',
    area: 'Katlicherra',
    routeId: 'route-hailakandi-01',
    latitude: 24.4605,
    longitude: 92.5705,
    geofenceRadiusMeters: 100,
    phone: '+91 9435228899',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },

  // Rural Cachar (Route 6)
  {
    id: 'doc-rur-01',
    name: 'Dr. Tapash Das',
    qualification: 'MD (Pediatrics)',
    specialty: 'Child Specialist',
    tier: 'B',
    clinicName: 'Lakhipur Mother & Child Clinic',
    clinicAddress: 'Subdivision Road, Lakhipur, Cachar 788103',
    district: 'Cachar',
    area: 'Lakhipur Subdivision',
    routeId: 'route-cachar-03',
    latitude: 24.7950,
    longitude: 93.0100,
    geofenceRadiusMeters: 100,
    phone: '+91 9435123456',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-rur-02',
    name: 'Dr. Gourango Paul',
    qualification: 'MD (Medicine)',
    specialty: 'Consultant Physician',
    tier: 'B',
    clinicName: 'Sonai Health Point',
    clinicAddress: 'Sonai Bazar Road, Cachar 788119',
    district: 'Cachar',
    area: 'Sonai Bazar',
    routeId: 'route-cachar-03',
    latitude: 24.7215,
    longitude: 92.8955,
    geofenceRadiusMeters: 100,
    phone: '+91 9435239900',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-rur-03',
    name: 'Dr. Monidipa Roy',
    qualification: 'MBBS, DGO',
    specialty: 'Women Health Specialist',
    tier: 'B',
    clinicName: 'Dholai Maternity Clinic',
    clinicAddress: 'Dholai Bazar, Cachar 788114',
    district: 'Cachar',
    area: 'Dholai',
    routeId: 'route-cachar-03',
    latitude: 24.6000,
    longitude: 92.8500,
    geofenceRadiusMeters: 100,
    phone: '+91 9435240011',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
];

export const MOCK_CHEMISTS: Chemist[] = [
  {
    id: 'chem-01',
    shopName: 'Janata Medical Hall',
    contactPerson: 'Kamal Das',
    drugLicenseNumber: 'AS-CAC-2022-20B-112',
    gstNumber: '18AAACJ1234F1Z1',
    district: 'Cachar',
    area: 'Hospital Road, Silchar',
    routeId: 'route-cachar-01',
    phone: '+91 9435011111',
    latitude: 24.8218,
    longitude: 92.7971,
  },
  {
    id: 'chem-02',
    shopName: 'Apollo Pharmacy SMCH Gate',
    contactPerson: 'Suman Roy',
    drugLicenseNumber: 'AS-CAC-2023-20B-554',
    gstNumber: '18AABCS9876G2Z2',
    district: 'Cachar',
    area: 'Ghungoor, Silchar',
    routeId: 'route-cachar-01',
    phone: '+91 9435022222',
    latitude: 24.7768,
    longitude: 92.7940,
  },
  {
    id: 'chem-03',
    shopName: 'Rangirkhari Medicos',
    contactPerson: 'Bijoy Paul',
    drugLicenseNumber: 'AS-CAC-2021-20B-883',
    gstNumber: '18AACCP3456H3Z3',
    district: 'Cachar',
    area: 'Rangirkhari, Silchar',
    routeId: 'route-cachar-02',
    phone: '+91 9435033333',
    latitude: 24.8145,
    longitude: 92.7918,
  },
  {
    id: 'chem-04',
    shopName: 'Surma Pharmacy (Shribhumi)',
    contactPerson: 'Nirmal Deb',
    drugLicenseNumber: 'AS-KXJ-2022-20B-401',
    gstNumber: '18AAECS4567J4Z4',
    district: 'Karimganj',
    area: 'Station Road, Karimganj',
    routeId: 'route-karimganj-01',
    phone: '+91 9435044444',
    latitude: 24.8688,
    longitude: 92.3558,
  },
  {
    id: 'chem-05',
    shopName: 'Hailakandi Central Medical Store',
    contactPerson: 'Dipak Nath',
    drugLicenseNumber: 'AS-HKD-2023-20B-209',
    gstNumber: '18AAEFN6789K5Z5',
    district: 'Hailakandi',
    area: 'Hospital Road, Hailakandi',
    routeId: 'route-hailakandi-01',
    phone: '+91 9435055555',
    latitude: 24.6838,
    longitude: 92.5672,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    brandName: 'CardioPulse-AM',
    genericName: 'Telmisartan 40mg + Amlodipine 5mg',
    category: 'Cardiology',
    dosageForm: 'Tablets',
    packSize: '10 x 10 ALU-ALU',
    mrp: 145.0,
    ptr: 103.57,
    pts: 93.21,
    gstRate: 12,
    availableStock: 450,
  },
  {
    id: 'prod-02',
    brandName: 'GlycoPulse-M500',
    genericName: 'Metformin SR 500mg + Glimepiride 2mg',
    category: 'Diabetology',
    dosageForm: 'Tablets',
    packSize: '10 x 15 Blister',
    mrp: 180.0,
    ptr: 128.57,
    pts: 115.71,
    gstRate: 12,
    availableStock: 620,
  },
  {
    id: 'prod-03',
    brandName: 'CefoPulse-CV 625',
    genericName: 'Amoxicillin 500mg + Clavulanic Acid 125mg',
    category: 'Anti-Infective',
    dosageForm: 'Tablets',
    packSize: '10 x 6 Strip',
    mrp: 220.0,
    ptr: 157.14,
    pts: 141.43,
    gstRate: 12,
    availableStock: 300,
  },
  {
    id: 'prod-04',
    brandName: 'OsteoPulse-D3 Max',
    genericName: 'Cholecalciferol 60000 IU',
    category: 'Orthopedics',
    dosageForm: 'Softgel Capsules',
    packSize: '10 x 4 Blister',
    mrp: 110.0,
    ptr: 78.57,
    pts: 70.71,
    gstRate: 12,
    availableStock: 800,
  },
  {
    id: 'prod-05',
    brandName: 'PanPulse-DSR',
    genericName: 'Pantoprazole 40mg + Domperidone 30mg SR',
    category: 'General',
    dosageForm: 'Capsules',
    packSize: '10 x 10 ALU-ALU',
    mrp: 135.0,
    ptr: 96.43,
    pts: 86.79,
    gstRate: 12,
    availableStock: 950,
  },
  {
    id: 'prod-06',
    brandName: 'RespPulse-LS Expectorant',
    genericName: 'Levosalbutamol + Ambroxol + Guaiphenesin',
    category: 'Respiratory',
    dosageForm: 'Syrup 100ml',
    packSize: '100ml Bottle',
    mrp: 95.0,
    ptr: 67.86,
    pts: 61.07,
    gstRate: 12,
    availableStock: 500,
  },
];

// Pre-approved 30-Day Monthly Tour Programme (MTP) for September 2026
export const SEPTEMBER_2026_MTP: MonthlyTourProgramme = {
  monthName: 'September',
  year: 2026,
  employeeId: 'usr-mr-barak-01',
  employeeName: 'Shakir Ahmad',
  territory: 'Barak Valley Division (Assam)',
  totalWorkingDays: 26,
  totalWeeklyOffs: 4,
  totalPlannedDoctorCalls: 240,
  totalPlannedChemistCalls: 96,
  approvalStatus: 'APPROVED_BY_RBM',
  approvedBy: 'Rajesh Sharma (RBM - East & Assam Zone)',
  days: [
    {
      dayNumber: 1,
      dateString: '01 Sep 2026',
      dayOfWeek: 'Tue',
      routeId: 'route-cachar-01',
      routeName: 'Silchar Central - SMCH & Hospital Road',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: true,
      accompaniedPerson: 'ABM_G_SOLANKI',
      accompaniedName: 'G Solanki (ABM)',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 2,
      dateString: '02 Sep 2026',
      dayOfWeek: 'Wed',
      routeId: 'route-cachar-02',
      routeName: 'Silchar North - Tarapur & Rangirkhari',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 3,
      dateString: '03 Sep 2026',
      dayOfWeek: 'Thu',
      routeId: 'route-karimganj-01',
      routeName: 'Karimganj Town & Station Road Hub (Shribhumi)',
      district: 'Karimganj',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: true,
      accompaniedPerson: 'ABM_G_SOLANKI',
      accompaniedName: 'G Solanki (ABM)',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 4,
      dateString: '04 Sep 2026',
      dayOfWeek: 'Fri',
      routeId: 'route-karimganj-02',
      routeName: 'Badarpur Junction & RK Nagar (Shribhumi)',
      district: 'Karimganj',
      targetDoctorCalls: 8,
      targetChemistCalls: 3,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 5,
      dateString: '05 Sep 2026',
      dayOfWeek: 'Sat',
      routeId: 'route-hailakandi-01',
      routeName: 'Hailakandi Main & Lala Bazar Belt',
      district: 'Hailakandi',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 6,
      dateString: '06 Sep 2026',
      dayOfWeek: 'Sun',
      routeId: 'route-sunday',
      routeName: 'Weekly Off (Sunday Rest & Sync)',
      district: 'HQ',
      targetDoctorCalls: 0,
      targetChemistCalls: 0,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'N/A',
      isSunday: true,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 7,
      dateString: '07 Sep 2026',
      dayOfWeek: 'Mon',
      routeId: 'route-cachar-01',
      routeName: 'Silchar Central - SMCH Ghungoor Clinics',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 8,
      dateString: '08 Sep 2026',
      dayOfWeek: 'Tue',
      routeId: 'route-cachar-01',
      routeName: 'Silchar Central - SMCH & Hospital Road',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 9,
      dateString: '09 Sep 2026',
      dayOfWeek: 'Wed',
      routeId: 'route-cachar-02',
      routeName: 'Silchar North - Meherpur & Malugram',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 10,
      dateString: '10 Sep 2026',
      dayOfWeek: 'Thu',
      routeId: 'route-cachar-03',
      routeName: 'Lakhipur & Sonai Rural Cachar Circuit',
      district: 'Cachar',
      targetDoctorCalls: 8,
      targetChemistCalls: 3,
      isJointWorking: true,
      accompaniedPerson: 'COLLEAGUE_AMIT_PAUL',
      accompaniedName: 'Amit Paul (Co-MR)',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 11,
      dateString: '11 Sep 2026',
      dayOfWeek: 'Fri',
      routeId: 'route-karimganj-01',
      routeName: 'Karimganj Town & Station Road Hub',
      district: 'Karimganj',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 12,
      dateString: '12 Sep 2026',
      dayOfWeek: 'Sat',
      routeId: 'route-hailakandi-01',
      routeName: 'Hailakandi S.K. Roy Hospital & Lala',
      district: 'Hailakandi',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 13,
      dateString: '13 Sep 2026',
      dayOfWeek: 'Sun',
      routeId: 'route-sunday',
      routeName: 'Weekly Off (Sunday Rest & Sync)',
      district: 'HQ',
      targetDoctorCalls: 0,
      targetChemistCalls: 0,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'N/A',
      isSunday: true,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 14,
      dateString: '14 Sep 2026',
      dayOfWeek: 'Mon',
      routeId: 'route-cachar-01',
      routeName: 'Silchar Central - Ambicapatty & Park Road',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 15,
      dateString: '15 Sep 2026',
      dayOfWeek: 'Tue',
      routeId: 'route-cachar-02',
      routeName: 'Silchar North - Tarapur & Sadarghat',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: true,
      accompaniedPerson: 'RBM_RAJESH_SHARMA',
      accompaniedName: 'Rajesh Sharma (RBM)',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 16,
      dateString: '16 Sep 2026',
      dayOfWeek: 'Wed',
      routeId: 'route-karimganj-01',
      routeName: 'Karimganj Town & Civil Hospital Corridor',
      district: 'Karimganj',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: true,
      accompaniedPerson: 'RBM_RAJESH_SHARMA',
      accompaniedName: 'Rajesh Sharma (RBM)',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 17,
      dateString: '17 Sep 2026',
      dayOfWeek: 'Thu',
      routeId: 'route-karimganj-02',
      routeName: 'Nilambazar & Patharkandi Circuit',
      district: 'Karimganj',
      targetDoctorCalls: 8,
      targetChemistCalls: 3,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 18,
      dateString: '18 Sep 2026',
      dayOfWeek: 'Fri',
      routeId: 'route-hailakandi-01',
      routeName: 'Hailakandi Main & Katlicherra Belt',
      district: 'Hailakandi',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 19,
      dateString: '19 Sep 2026',
      dayOfWeek: 'Sat',
      routeId: 'route-cachar-03',
      routeName: 'Udharbond & Borkhola Health Centers',
      district: 'Cachar',
      targetDoctorCalls: 8,
      targetChemistCalls: 3,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 20,
      dateString: '20 Sep 2026',
      dayOfWeek: 'Sun',
      routeId: 'route-sunday',
      routeName: 'Weekly Off (Sunday Rest & Sync)',
      district: 'HQ',
      targetDoctorCalls: 0,
      targetChemistCalls: 0,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'N/A',
      isSunday: true,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 21,
      dateString: '21 Sep 2026',
      dayOfWeek: 'Mon',
      routeId: 'route-cachar-01',
      routeName: 'Silchar Central - SMCH Ghungoor Block',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 22,
      dateString: '22 Sep 2026',
      dayOfWeek: 'Tue',
      routeId: 'route-cachar-02',
      routeName: 'Silchar North - Rangirkhari & Meherpur',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 23,
      dateString: '23 Sep 2026',
      dayOfWeek: 'Wed',
      routeId: 'route-karimganj-01',
      routeName: 'Karimganj Town & Settlement Area',
      district: 'Karimganj',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 24,
      dateString: '24 Sep 2026',
      dayOfWeek: 'Thu',
      routeId: 'route-karimganj-02',
      routeName: 'Badarpur Junction & RK Nagar Hub',
      district: 'Karimganj',
      targetDoctorCalls: 8,
      targetChemistCalls: 3,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 25,
      dateString: '25 Sep 2026',
      dayOfWeek: 'Fri',
      routeId: 'route-hailakandi-01',
      routeName: 'Hailakandi Town & Lala Bazar',
      district: 'Hailakandi',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: true,
      accompaniedPerson: 'ABM_G_SOLANKI',
      accompaniedName: 'G Solanki (ABM)',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 26,
      dateString: '26 Sep 2026',
      dayOfWeek: 'Sat',
      routeId: 'route-cachar-03',
      routeName: 'Lakhipur & Sonai Tea Belt Clinics',
      district: 'Cachar',
      targetDoctorCalls: 8,
      targetChemistCalls: 3,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 27,
      dateString: '27 Sep 2026',
      dayOfWeek: 'Sun',
      routeId: 'route-sunday',
      routeName: 'Weekly Off (Sunday Rest & Sync)',
      district: 'HQ',
      targetDoctorCalls: 0,
      targetChemistCalls: 0,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'N/A',
      isSunday: true,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 28,
      dateString: '28 Sep 2026',
      dayOfWeek: 'Mon',
      routeId: 'route-cachar-01',
      routeName: 'Silchar Central - Hospital Road Core Polyclinics',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 29,
      dateString: '29 Sep 2026',
      dayOfWeek: 'Tue',
      routeId: 'route-cachar-02',
      routeName: 'Silchar North - Valley Hospital & Tarapur',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 30,
      dateString: '30 Sep 2026',
      dayOfWeek: 'Wed',
      routeId: 'route-cachar-01',
      routeName: 'Silchar Central - Month-End Secondary Order Closures',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 6,
      isJointWorking: true,
      accompaniedPerson: 'ABM_G_SOLANKI',
      accompaniedName: 'G Solanki (ABM)',
      isSunday: false,
      status: 'SCHEDULED',
    },
  ],
};

export const CURRENT_USER_MOCK = CURRENT_USER;
export const DOCTORS_MOCK = MOCK_DOCTORS;
export const CHEMISTS_MOCK = MOCK_CHEMISTS;
export const PRODUCTS_MOCK = MOCK_PRODUCTS;
