/**
 * RepPulse Barak Division (Assam) Enterprise Mock Data
 * Realistic medical infrastructure for Cachar (Silchar), Karimganj, and Hailakandi
 */

import { Doctor, Chemist, Product, UserProfile, RoutePlan, Hospital, StockistFirm } from '../types';

export const CURRENT_USER: UserProfile = {
  id: 'usr-mr-barak-01',
  name: 'Shakir Ahmad',
  email: 'shakirahmad878@gmail.com',
  role: 'MEDICAL_REP',
  employeeCode: 'REP-AS-904',
  territory: 'Barak Valley Division (Assam)',
  headquarter: 'Silchar HQ',
  phone: '+91 8448440654',
  assignedRouteIds: ['route-cachar-01', 'route-cachar-02', 'route-karimganj-01', 'route-hailakandi-01'],
  activeRouteId: 'route-cachar-01',
};

export const BARAK_ROUTES: RoutePlan[] = [
  {
    id: 'route-cachar-01',
    code: 'ROUTE-SIL-01',
    name: 'Silchar Central - SMCH & Hospital Road',
    district: 'Cachar',
    areas: ['SMCH Ghungoor', 'Hospital Road', 'Park Road', 'Ambicapatty'],
    totalDoctors: 12,
    totalHospitals: 3,
    totalChemists: 15,
    isAssigned: true,
    isActiveToday: true,
    description: 'High-density tertiary care corridor covering Silchar Medical College & Hospital and Hospital Road polyclinics.',
  },
  {
    id: 'route-cachar-02',
    code: 'ROUTE-SIL-02',
    name: 'Silchar North - Tarapur, Rangirkhari & Meherpur',
    district: 'Cachar',
    areas: ['Tarapur', 'Rangirkhari', 'Meherpur', 'Malugram', 'Sadarghat'],
    totalDoctors: 10,
    totalHospitals: 2,
    totalChemists: 14,
    isAssigned: true,
    isActiveToday: false,
    description: 'Commercial and residential clinic belt including Green Heals Hospital and Nightingale Hospital.',
  },
  {
    id: 'route-karimganj-01',
    code: 'ROUTE-KXJ-01',
    name: 'Karimganj Town & Station Road Hub',
    district: 'Karimganj',
    areas: ['Station Road', 'Civil Hospital Road', 'Settlement Area', 'Main Road'],
    totalDoctors: 8,
    totalHospitals: 2,
    totalChemists: 12,
    isAssigned: true,
    isActiveToday: false,
    description: 'Border district town hub centered around Karimganj Civil Hospital and major wholesale stockists.',
  },
  {
    id: 'route-karimganj-02',
    code: 'ROUTE-BDP-02',
    name: 'Badarpur Junction & Ram Krishna Nagar',
    district: 'Karimganj',
    areas: ['Badarpur Railway Town', 'Nilambazar', 'Ram Krishna Nagar', 'Patharkandi'],
    totalDoctors: 6,
    totalHospitals: 1,
    totalChemists: 9,
    isAssigned: false,
    isActiveToday: false,
    description: 'Railway junction market and peripheral healthcare clinics.',
  },
  {
    id: 'route-hailakandi-01',
    code: 'ROUTE-HKD-01',
    name: 'Hailakandi Main & Lala Bazar Belt',
    district: 'Hailakandi',
    areas: ['S.K. Roy Hospital Road', 'Station Road', 'Rabindra Sarani', 'Lala Bazar'],
    totalDoctors: 8,
    totalHospitals: 2,
    totalChemists: 11,
    isAssigned: true,
    isActiveToday: false,
    description: 'Hailakandi district headquarters and south Barak retail pharmacy cluster.',
  },
  {
    id: 'route-cachar-03',
    code: 'ROUTE-RURAL-03',
    name: 'Lakhipur & Sonai Rural Cachar Circuit',
    district: 'Cachar',
    areas: ['Lakhipur Town', 'Sonai Bazar', 'Dholai', 'Udharbond', 'Katigorah'],
    totalDoctors: 6,
    totalHospitals: 2,
    totalChemists: 10,
    isAssigned: false,
    isActiveToday: false,
    description: 'Rural tea-garden belt and subdivision health centers in east Cachar.',
  },
];

export const BARAK_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-01',
    name: 'Silchar Medical College & Hospital (SMCH)',
    type: 'GOVERNMENT_MEDICAL_COLLEGE',
    district: 'Cachar',
    area: 'Ghungoor, Silchar',
    address: 'Ghungoor, Silchar, Cachar, Assam 788014',
    bedCount: 1000,
    keyDoctorsCount: 18,
    latitude: 24.7766,
    longitude: 92.7938,
    phone: '+91 3842 229110',
    routeId: 'route-cachar-01',
  },
  {
    id: 'hosp-02',
    name: 'Valley Hospital & Research Centre',
    type: 'PRIVATE_HOSPITAL',
    district: 'Cachar',
    area: 'Meherpur, Silchar',
    address: 'National Highway 54, Meherpur, Silchar, Assam 788015',
    bedCount: 150,
    keyDoctorsCount: 8,
    latitude: 24.8012,
    longitude: 92.7845,
    phone: '+91 3842 242000',
    routeId: 'route-cachar-02',
  },
  {
    id: 'hosp-03',
    name: 'Green Heals Hospital',
    type: 'PRIVATE_HOSPITAL',
    district: 'Cachar',
    area: 'Hospital Road, Silchar',
    address: 'Hospital Road, Ambicapatty, Silchar, Assam 788005',
    bedCount: 120,
    keyDoctorsCount: 7,
    latitude: 24.8219,
    longitude: 92.7972,
    phone: '+91 3842 233444',
    routeId: 'route-cachar-01',
  },
  {
    id: 'hosp-04',
    name: 'Nightingale Hospital & Nursing Home',
    type: 'NURSING_HOME',
    district: 'Cachar',
    area: 'Rangirkhari, Silchar',
    address: 'Rangirkhari Point, Silchar, Assam 788005',
    bedCount: 80,
    keyDoctorsCount: 5,
    latitude: 24.8142,
    longitude: 92.7911,
    phone: '+91 3842 260111',
    routeId: 'route-cachar-02',
  },
  {
    id: 'hosp-05',
    name: 'Karimganj Civil Hospital',
    type: 'CIVIL_HOSPITAL',
    district: 'Karimganj',
    area: 'Civil Hospital Road, Karimganj',
    address: 'Civil Hospital Road, Karimganj, Assam 788710',
    bedCount: 200,
    keyDoctorsCount: 6,
    latitude: 24.8682,
    longitude: 92.3551,
    phone: '+91 3843 262222',
    routeId: 'route-karimganj-01',
  },
  {
    id: 'hosp-06',
    name: 'S.K. Roy Civil Hospital',
    type: 'CIVIL_HOSPITAL',
    district: 'Hailakandi',
    area: 'Hospital Road, Hailakandi',
    address: 'Hailakandi Town, Assam 788151',
    bedCount: 150,
    keyDoctorsCount: 5,
    latitude: 24.6833,
    longitude: 92.5667,
    phone: '+91 3844 222111',
    routeId: 'route-hailakandi-01',
  },
];

export const BARAK_FIRMS: StockistFirm[] = [
  {
    id: 'firm-01',
    name: 'Barak Pharma Distributors',
    contactPerson: 'Pradip Roy',
    type: 'SUPER_STOCKIST',
    dlNumber: 'AS-CAC-2023-DL-0891',
    gstNumber: '18AAACB1234F1Z1',
    district: 'Cachar',
    area: 'Hospital Road, Silchar',
    address: '42 Hospital Road, Near Lion Club, Silchar 788005',
    phone: '+91 9435071234',
    routeId: 'route-cachar-01',
  },
  {
    id: 'firm-02',
    name: 'Cachar Drug Agencies',
    contactPerson: 'Debashis Paul',
    type: 'AUTHORIZED_DISTRIBUTOR',
    dlNumber: 'AS-CAC-2022-DL-0452',
    gstNumber: '18AACCD5678G2Z4',
    district: 'Cachar',
    area: 'Tarapur, Silchar',
    address: 'Station Road, Tarapur, Silchar 788003',
    phone: '+91 9435175678',
    routeId: 'route-cachar-02',
  },
  {
    id: 'firm-03',
    name: 'Surma Valley Medical Syndicate',
    contactPerson: 'Alok Choudhury',
    type: 'WHOLESALE_PHARMA',
    dlNumber: 'AS-KXJ-2021-DL-0311',
    gstNumber: '18AAECS9012H3Z9',
    district: 'Karimganj',
    area: 'Settlement Road, Karimganj',
    address: 'Settlement Road, Near Old Court, Karimganj 788710',
    phone: '+91 9435278901',
    routeId: 'route-karimganj-01',
  },
  {
    id: 'firm-04',
    name: 'Barak Medico Agencies',
    contactPerson: 'Sudhir Nath',
    type: 'AUTHORIZED_DISTRIBUTOR',
    dlNumber: 'AS-HKD-2024-DL-0199',
    gstNumber: '18AAEFN3456J4Z7',
    district: 'Hailakandi',
    area: 'Station Road, Hailakandi',
    address: 'Station Road, Hailakandi Town 788151',
    phone: '+91 9435371122',
    routeId: 'route-hailakandi-01',
  },
];

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: 'doc-barak-01',
    name: 'Dr. Sanjay Solanki',
    qualification: 'MD (General Medicine), DM (Cardiology)',
    specialty: 'Cardiologist',
    tier: 'A_PLUS',
    clinicName: 'Silchar Heart & Vascular Care Centre',
    clinicAddress: '14 Hospital Road, Ambicapatty, Silchar 788005',
    district: 'Cachar',
    area: 'Hospital Road',
    routeId: 'route-cachar-01',
    latitude: 24.8215,
    longitude: 92.7970,
    geofenceRadiusMeters: 100,
    phone: '+91 9435012345',
    monthlyVisitTarget: 10,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-barak-02',
    name: 'Dr. Vijay Thakur',
    qualification: 'MS (Orthopedics), M.Ch (Joint Replacement)',
    specialty: 'Orthopedic Surgeon',
    tier: 'A_PLUS',
    clinicName: 'Barak Ortho Spine & Trauma Clinic',
    clinicAddress: 'Opposite SMCH Main Gate, Ghungoor, Silchar 788014',
    district: 'Cachar',
    area: 'SMCH Ghungoor',
    routeId: 'route-cachar-01',
    latitude: 24.7770,
    longitude: 92.7942,
    geofenceRadiusMeters: 100,
    phone: '+91 9435023456',
    monthlyVisitTarget: 10,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-barak-03',
    name: 'Dr. Debashis Nath',
    qualification: 'MD (Pediatrics), DCH',
    specialty: 'Pediatrician',
    tier: 'A',
    clinicName: 'Cachar Children Care Clinic',
    clinicAddress: 'Park Road, Near Normal School, Silchar 788001',
    district: 'Cachar',
    area: 'Park Road',
    routeId: 'route-cachar-01',
    latitude: 24.8250,
    longitude: 92.7990,
    geofenceRadiusMeters: 100,
    phone: '+91 9435034567',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 2,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-barak-04',
    name: 'Dr. Ratan Paul',
    qualification: 'MD (Internal Medicine)',
    specialty: 'Consultant Physician',
    tier: 'A',
    clinicName: 'Green Heals Poly Clinic',
    clinicAddress: 'Hospital Road, Ambicapatty, Silchar 788005',
    district: 'Cachar',
    area: 'Hospital Road',
    routeId: 'route-cachar-01',
    latitude: 24.8220,
    longitude: 92.7975,
    geofenceRadiusMeters: 100,
    phone: '+91 9435045678',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 3,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-barak-05',
    name: 'Dr. Anupama Bhattacharjee',
    qualification: 'MD (Obstetrics & Gynecology), DGO',
    specialty: 'Gynecologist',
    tier: 'A_PLUS',
    clinicName: 'Matri Kalyan Clinic',
    clinicAddress: 'Rangirkhari Point, Silchar 788005',
    district: 'Cachar',
    area: 'Rangirkhari',
    routeId: 'route-cachar-02',
    latitude: 24.8140,
    longitude: 92.7915,
    geofenceRadiusMeters: 100,
    phone: '+91 9435056789',
    monthlyVisitTarget: 10,
    completedVisitsThisMonth: 1,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-barak-06',
    name: 'Dr. Subhashish Deb',
    qualification: 'MS (General Surgery), FIAGES',
    specialty: 'General Surgeon',
    tier: 'A',
    clinicName: 'Valley Research Chamber',
    clinicAddress: 'Meherpur, Silchar 788015',
    district: 'Cachar',
    area: 'Meherpur',
    routeId: 'route-cachar-02',
    latitude: 24.8015,
    longitude: 92.7850,
    geofenceRadiusMeters: 100,
    phone: '+91 9435067890',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-barak-07',
    name: 'Dr. Nilanjan Roy',
    qualification: 'MD (Dermatology, Venereology & Leprosy)',
    specialty: 'Dermatologist',
    tier: 'B',
    clinicName: 'Tarapur Skin & Laser Care',
    clinicAddress: 'Station Road, Tarapur, Silchar 788003',
    district: 'Cachar',
    area: 'Tarapur',
    routeId: 'route-cachar-02',
    latitude: 24.8320,
    longitude: 92.7880,
    geofenceRadiusMeters: 100,
    phone: '+91 9435078901',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: false,
  },
  {
    id: 'doc-barak-08',
    name: 'Dr. Sourav Choudhury',
    qualification: 'MD (Chest Medicine), FCCP',
    specialty: 'Pulmonologist',
    tier: 'A',
    clinicName: 'Karimganj Chest & Asthma Clinic',
    clinicAddress: 'Civil Hospital Road, Karimganj 788710',
    district: 'Karimganj',
    area: 'Civil Hospital Road',
    routeId: 'route-karimganj-01',
    latitude: 24.8685,
    longitude: 92.3555,
    geofenceRadiusMeters: 100,
    phone: '+91 9435089012',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 1,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-barak-09',
    name: 'Dr. Monojit Roy',
    qualification: 'MD (General Medicine)',
    specialty: 'Physician & Diabetologist',
    tier: 'A',
    clinicName: 'Surma Medical Chamber',
    clinicAddress: 'Station Road, Near Town Club, Karimganj 788710',
    district: 'Karimganj',
    area: 'Station Road',
    routeId: 'route-karimganj-01',
    latitude: 24.8690,
    longitude: 92.3560,
    geofenceRadiusMeters: 100,
    phone: '+91 9435090123',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-barak-10',
    name: 'Dr. Pranab Nath',
    qualification: 'MD (Medicine), DM (Gastroenterology)',
    specialty: 'Gastroenterologist',
    tier: 'A_PLUS',
    clinicName: 'Hailakandi Gastro Liver Clinic',
    clinicAddress: 'Hospital Road, Near S.K. Roy Hospital, Hailakandi 788151',
    district: 'Hailakandi',
    area: 'Hospital Road',
    routeId: 'route-hailakandi-01',
    latitude: 24.6835,
    longitude: 92.5670,
    geofenceRadiusMeters: 100,
    phone: '+91 9435101234',
    monthlyVisitTarget: 8,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-barak-11',
    name: 'Dr. Bikramjit Sinha',
    qualification: 'MS (ENT), DLO',
    specialty: 'ENT Specialist',
    tier: 'B',
    clinicName: 'Lala Bazar Health Clinic',
    clinicAddress: 'Main Road, Lala Bazar, Hailakandi 788163',
    district: 'Hailakandi',
    area: 'Lala Bazar',
    routeId: 'route-hailakandi-01',
    latitude: 24.5500,
    longitude: 92.6000,
    geofenceRadiusMeters: 100,
    phone: '+91 9435112345',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: true,
  },
  {
    id: 'doc-barak-12',
    name: 'Dr. Tapash Das',
    qualification: 'MD (Pediatrics)',
    specialty: 'Child Specialist',
    tier: 'B',
    clinicName: 'Lakhipur Mother & Child Clinic',
    clinicAddress: 'Subdivision Road, Lakhipur, Cachar 788103',
    district: 'Cachar',
    area: 'Lakhipur Town',
    routeId: 'route-cachar-03',
    latitude: 24.7950,
    longitude: 93.0100,
    geofenceRadiusMeters: 100,
    phone: '+91 9435123456',
    monthlyVisitTarget: 6,
    completedVisitsThisMonth: 0,
    todayVisitStatus: 'PENDING',
    isAssignedToMe: false,
  },
];

export const MOCK_CHEMISTS: Chemist[] = [
  {
    id: 'chem-01',
    shopName: 'Janata Medical Hall',
    contactPerson: 'Kamal Das',
    drugLicenseNumber: 'AS-CAC-2022-20B-112',
    gstNumber: '18AAACJ1234F1Z1',
    district: 'Cachar',
    area: 'Hospital Road, Silchar',
    routeId: 'route-cachar-01',
    phone: '+91 9435011111',
    latitude: 24.8218,
    longitude: 92.7971,
  },
  {
    id: 'chem-02',
    shopName: 'Apollo Pharmacy SMCH Gate',
    contactPerson: 'Suman Roy',
    drugLicenseNumber: 'AS-CAC-2023-20B-554',
    gstNumber: '18AABCS9876G2Z2',
    district: 'Cachar',
    area: 'Ghungoor, Silchar',
    routeId: 'route-cachar-01',
    phone: '+91 9435022222',
    latitude: 24.7768,
    longitude: 92.7940,
  },
  {
    id: 'chem-03',
    shopName: 'Rangirkhari Medicos',
    contactPerson: 'Bijoy Paul',
    drugLicenseNumber: 'AS-CAC-2021-20B-883',
    gstNumber: '18AACCP3456H3Z3',
    district: 'Cachar',
    area: 'Rangirkhari, Silchar',
    routeId: 'route-cachar-02',
    phone: '+91 9435033333',
    latitude: 24.8145,
    longitude: 92.7918,
  },
  {
    id: 'chem-04',
    shopName: 'Surma Pharmacy',
    contactPerson: 'Nirmal Deb',
    drugLicenseNumber: 'AS-KXJ-2022-20B-401',
    gstNumber: '18AAECS4567J4Z4',
    district: 'Karimganj',
    area: 'Station Road, Karimganj',
    routeId: 'route-karimganj-01',
    phone: '+91 9435044444',
    latitude: 24.8688,
    longitude: 92.3558,
  },
  {
    id: 'chem-05',
    shopName: 'Hailakandi Central Medical Store',
    contactPerson: 'Dipak Nath',
    drugLicenseNumber: 'AS-HKD-2023-20B-209',
    gstNumber: '18AAEFN6789K5Z5',
    district: 'Hailakandi',
    area: 'Hospital Road, Hailakandi',
    routeId: 'route-hailakandi-01',
    phone: '+91 9435055555',
    latitude: 24.6838,
    longitude: 92.5672,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    brandName: 'CardioPulse-AM',
    genericName: 'Telmisartan 40mg + Amlodipine 5mg',
    category: 'Cardiology',
    dosageForm: 'Tablets',
    packSize: '10 x 10 ALU-ALU',
    mrp: 145.0,
    ptr: 103.57,
    pts: 93.21,
    gstRate: 12,
    availableStock: 450,
  },
  {
    id: 'prod-02',
    brandName: 'GlycoPulse-M500',
    genericName: 'Metformin SR 500mg + Glimepiride 2mg',
    category: 'Diabetology',
    dosageForm: 'Tablets',
    packSize: '10 x 15 Blister',
    mrp: 180.0,
    ptr: 128.57,
    pts: 115.71,
    gstRate: 12,
    availableStock: 620,
  },
  {
    id: 'prod-03',
    brandName: 'CefoPulse-CV 625',
    genericName: 'Amoxicillin 500mg + Clavulanic Acid 125mg',
    category: 'Anti-Infective',
    dosageForm: 'Tablets',
    packSize: '10 x 6 Strip',
    mrp: 220.0,
    ptr: 157.14,
    pts: 141.43,
    gstRate: 12,
    availableStock: 300,
  },
  {
    id: 'prod-04',
    brandName: 'OsteoPulse-D3 Max',
    genericName: 'Cholecalciferol 60000 IU',
    category: 'Orthopedics',
    dosageForm: 'Softgel Capsules',
    packSize: '10 x 4 Blister',
    mrp: 110.0,
    ptr: 78.57,
    pts: 70.71,
    gstRate: 12,
    availableStock: 800,
  },
  {
    id: 'prod-05',
    brandName: 'PanPulse-DSR',
    genericName: 'Pantoprazole 40mg + Domperidone 30mg SR',
    category: 'General',
    dosageForm: 'Capsules',
    packSize: '10 x 10 ALU-ALU',
    mrp: 135.0,
    ptr: 96.43,
    pts: 86.79,
    gstRate: 12,
    availableStock: 950,
  },
  {
    id: 'prod-06',
    brandName: 'RespPulse-LS Expectorant',
    genericName: 'Levosalbutamol + Ambroxol + Guaiphenesin',
    category: 'Respiratory',
    dosageForm: 'Syrup 100ml',
    packSize: '100ml Bottle',
    mrp: 95.0,
    ptr: 67.86,
    pts: 61.07,
    gstRate: 12,
    availableStock: 500,
  },
];

export const CURRENT_USER_MOCK = CURRENT_USER;
export const DOCTORS_MOCK = MOCK_DOCTORS;
export const CHEMISTS_MOCK = MOCK_CHEMISTS;
export const PRODUCTS_MOCK = MOCK_PRODUCTS;
